spring.application.name=the-uco-experience
server.port=8080

spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1434;databaseName=ucoexperience;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:UcoExperience2026!}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.sql.init.mode=always
spring.sql.init.platform=sqlserver